{
 "title": "LTE Monitor",
 "description": "Dashboard for the software to monitor the status of a LinkHub LTE modem via Prometheus and Grafana.\n\nSee: https://github.com/SimonPrinz/LTEMonitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connection Time",
   "type": "stat",
   "description": "Current time of the active connection",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "connection_time", "legendFormat": "{{ipv4}}" }
   ]
  },
  {
   "title": "Connected Devices",
   "type": "gauge",
   "description": "Up to 32 devices:\nhttps://www.alcatelmobile.com/caribbean/product/mobile-broadband/mobile-wifi/linkhub-lte-cat7-home-station/",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Devices" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "lan_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RSRP",
   "type": "gauge",
   "description": "Reference Signal Received Power\n\nThe power level of LTE reference signals (used for synchronization and channel estimation).",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_signal{type=\"rsrp\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RSRQ",
   "type": "gauge",
   "description": "Reference Signal Received Quality\n\nThe quality of the received reference signal, taking into account interference and noise.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_signal{type=\"rsrq\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "description": "Received Signal Strength Indicator\n\nTotal received power (desired signal + noise + interference).",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_signal{type=\"rssi\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "SINR",
   "type": "gauge",
   "description": "Signal to Interference plus Noise Ratio\n\nThe ratio of useful signal power to the sum of interference power and noise.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_signal{type=\"sinr\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bytes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "connection_bytes", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "connection_rate", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Speed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "connection_speed", "legendFormat": "{{direction}}" }
   ]
  },
  {
   "title": "Signal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Signal",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "dBm" } },
     "targets": [
      { "expr": "network_signal", "legendFormat": "{{type}}" }
     ]
    }
   ]
  },
  {
   "title": "Connection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "connection_bytes", "legendFormat": "{{direction}}" }
     ]
    },
    {
     "title": "Speed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expr": "connection_speed", "legendFormat": "{{direction}}" }
     ]
    }
   ]
  }
 ]
}